#!/bin/bash
echo "Running PHP CS Fixer using Docker with PHP 8.1..."

docker run --rm \
  -v "$(pwd):/app" \
  -w /app \
  php:8.1-cli \
  ./vendor/bin/php-cs-fixer fix .

if [ $? -ne 0 ]; then
  echo "PHP CS Fixer failed!"
  exit 1
fi

git add -u

exit 0
